"""Integration registry mapping integration keys to platform configuration."""

REGISTRY: dict = {
    "braze": {
        "display_name": "Braze",
        "android": {
            "repo":                  "rudderlabs/rudder-integration-braze-android",
            "maven_group":           "com.rudderstack.android.integration",
            "maven_artifact":        "braze",
            "build_file":            "braze/build.gradle",
            "vendor_group":          "com.braze",
            "vendor_artifact":       "android-sdk-ui",
            "vendor_repo":           "braze-inc/braze-android-sdk",
            "vendor_version_file":   "build.gradle",
        },
        "ios": {
            "repo":                  "rudderlabs/rudder-integration-braze-ios",
            "pod":                   "Rudder-Braze",
            "podspec_file":          "Rudder-Braze.podspec",
            "package_json_file":     "package.json",
            "vendor_pod":            "BrazeKit",
            "vendor_gh_repo":        "braze-inc/braze-swift-sdk",
            "vendor_version_file":   "BrazeKit.podspec",
        },
        "rn": {
            "rudder_repo":                  "rudderlabs/rudder-sdk-react-native",
            "rudder_pkg":                   "@rudderstack/rudder-integration-braze-react-native",
            "rudder_android_file":          "libs/rudder-integration-braze-react-native/android/build.gradle",
            "rudder_ios_file":              "libs/rudder-integration-braze-react-native/rudder-integration-braze-react-native.podspec",
            "rudder_android_dep_group":     "com.rudderstack.android.integration",
            "rudder_android_dep_artifact":  "braze",
            "rudder_ios_dep_pod":           "Rudder-Braze",
            "vendor_pkg":                   "@braze/react-native-sdk",
            "vendor_repo":                  "braze-inc/braze-react-native-sdk",
            "vendor_android_file":          "android/build.gradle",
            "vendor_ios_file":              "braze-react-native-sdk.podspec",
            "vendor_android_dep_group":     "com.braze",
            "vendor_android_dep_artifact":  "android-sdk-ui",
            "vendor_ios_dep_pod":           "BrazeKit",
        },
        "flutter": {
            "rudder_repo":                  "rudderlabs/rudder-sdk-flutter",
            "rudder_pkg":                   "rudder_integration_braze_flutter",
            "rudder_android_file":          "packages/integrations/rudder_integration_braze_flutter/android/build.gradle",
            "rudder_ios_file":              "packages/integrations/rudder_integration_braze_flutter/ios/rudder_integration_braze_flutter.podspec",
            "rudder_android_dep_group":     "com.rudderstack.android.integration",
            "rudder_android_dep_artifact":  "braze",
            "rudder_ios_dep_pod":           "Rudder-Braze",
            "vendor_pkg":                   "braze_plugin",
            "vendor_repo":                  "braze-inc/braze-flutter-sdk",
            "vendor_android_file":          "android/build.gradle",
            "vendor_ios_file":              "ios/braze_plugin.podspec",
            "vendor_android_dep_group":     "com.braze",
            "vendor_android_dep_artifact":  "android-sdk-ui",
            "vendor_ios_dep_pod":           "BrazeKit",
        },
    },
    "adjust": {
        "display_name": "Adjust",
        "android": {
            "repo":                  "rudderlabs/rudder-integration-adjust-android",
            "maven_group":           "com.rudderstack.android.integration",
            "maven_artifact":        "adjust",
            "build_file":            "adjust/build.gradle",
            "vendor_group":          "com.adjust.sdk",
            "vendor_artifact":       "adjust-android",
            "vendor_repo":           "adjust/android_sdk",
            "vendor_version_file":   "Adjust/build.gradle",
        },
        "ios": {
            "repo":                  "rudderlabs/rudder-integration-adjust-ios",
            "pod":                   "Rudder-Adjust",
            "podspec_file":          "Rudder-Adjust.podspec",
            "package_json_file":     "package.json",
            "vendor_pod":            "Adjust",
            "vendor_gh_repo":        "adjust/ios_sdk",
            "vendor_version_file":   "Adjust.podspec",
        },
        "rn": None,  # No Adjust integration in RN monorepo
        "flutter": {
            "rudder_repo":                  "rudderlabs/rudder-sdk-flutter",
            "rudder_pkg":                   "rudder_integration_adjust_flutter",
            "rudder_android_file":          "packages/integrations/rudder_integration_adjust_flutter/android/build.gradle",
            "rudder_ios_file":              "packages/integrations/rudder_integration_adjust_flutter/ios/rudder_integration_adjust_flutter.podspec",
            "rudder_android_dep_group":     "com.rudderstack.android.integration",
            "rudder_android_dep_artifact":  "adjust",
            "rudder_ios_dep_pod":           "Rudder-Adjust",
            "vendor_pkg":                   "adjust_sdk",
            "vendor_repo":                  "adjust/flutter_sdk",
            "vendor_android_file":          "android/build.gradle",
            "vendor_ios_file":              "ios/adjust_sdk.podspec",
            "vendor_android_dep_group":     "com.adjust.sdk",
            "vendor_android_dep_artifact":  "adjust-android",
            "vendor_ios_dep_pod":           "Adjust",
        },
    },
    "firebase": {
        "display_name": "Firebase",
        "android": {
            "repo":                  "rudderlabs/rudder-integration-firebase-android",
            "maven_group":           "com.rudderstack.android.integration",
            "maven_artifact":        "firebase",
            "build_file":            "firebase/build.gradle",
            "vendor_group":          "com.google.firebase",
            "vendor_artifact":       "firebase-bom",
            "vendor_repo":           "firebase/firebase-android-sdk",
            "vendor_maven_repo":     "google",
            "vendor_latest_url":     "https://firebase.google.com/support/release-notes/android",
        },
        "ios": {
            "repo":                  "rudderlabs/rudder-integration-firebase-ios",
            "pod":                   "Rudder-Firebase",
            "podspec_file":          "Rudder-Firebase.podspec",
            "package_json_file":     "package.json",
            "vendor_pod":            "FirebaseAnalytics",
            "vendor_gh_repo":        "firebase/firebase-ios-sdk",
            "vendor_version_file":   "FirebaseAnalytics.podspec",
        },
        "rn": {
            "rudder_repo":                  "rudderlabs/rudder-sdk-react-native",
            "rudder_pkg":                   "@rudderstack/rudder-integration-firebase-react-native",
            "rudder_android_file":          "libs/rudder-integration-firebase-react-native/android/build.gradle",
            "rudder_ios_file":              "libs/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec",
            "rudder_android_dep_group":     "com.rudderstack.android.integration",
            "rudder_android_dep_artifact":  "firebase",
            "rudder_ios_dep_pod":           "Rudder-Firebase",
            "vendor_pkg":                   "@react-native-firebase/analytics",
            "vendor_repo":                  "invertase/react-native-firebase",
            "vendor_android_file":          "packages/analytics/android/build.gradle",
            "vendor_ios_file":              "packages/analytics/RNFBAnalytics.podspec",
            "vendor_android_dep_group":     "com.google.firebase",
            "vendor_android_dep_artifact":  "firebase-bom",
            "vendor_ios_dep_pod":           "FirebaseAnalytics",
        },
        "flutter": None,
    },
}
